# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4ZM_51NIxfUPA3zxrtUgOAo4bD7d3nP
"""

import pandas as pd

p=pd.read_csv(r'/content/train.csv')

p

p.head()

p.tail()

p.shape

p.info()

p.isnull().sum()

p.index

p.describe().T

p.columns

import seaborn as sns
import matplotlib.pyplot as plt

for i in p.columns:
  sns.displot(p[i])

p.corr()

sns.heatmap(p.corr(),annot=True,cmap='Blues')

import numpy as np

log_trans = np.exp(p['battery_power'])

sns.displot(log_trans)

